# Generated by Django 4.0.3 on 2022-05-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0002_alter_dictionary_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='transcription',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
